### ISSUE TITLE
从远程win下载文件报错

### ISSUE THREAD

**Issue by brucmao** [trzsz/trzsz-go#15]
```
tsz .\Whore.flac
illegal base64 data at input byte 9355
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.18.3/x64/src/runtime/debug/stack.go:24 +0x65
github.com/trzsz/trzsz-go/trzsz.NewTrzszError({0xc0000160f0, 0x44}, {0xc0004fc05c, 0x4}, 0x1)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/comm.go:171 +0x272
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).recvCheck(0x2450?, {0x1e310c, 0x4}, 0x49?, 0xc000057ad0?)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/transfer.go:197 +0x16a
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).recvInteger(0xc000057c40?, {0x1e310c?, 0x2000?}, 0x0?)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/transfer.go:208 +0x25
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).checkInteger(0xc000057c40?, 0x2000)       [History]
        /home/runner/work/trzsz-go/trzsz-go/trzsz/transfer.go:216 +0x30
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).sendFiles(0xc00004c120, {0xc0000060b0, 0x1, 0x0?}, {0x0?, 0x0?})
        /home/runner/work/trzsz-go/trzsz-go/trzsz/transfer.go:584 +0x8a6
github.com/trzsz/trzsz-go/trzsz.sendFiles(0xc00004c120?, {0xc0000060b0, 0x1, 0x1}, 0xc000124c30, 0x21675d20108?, 0x60?)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/tsz.go:88 +0x19f
github.com/trzsz/trzsz-go/trzsz.TszMain()
        /home/runner/work/trzsz-go/trzsz-go/trzsz/tsz.go:167 +0x7f6
main.main()
        /home/runner/work/trzsz-go/trzsz-go/cmd/tsz/main.go:33 +0x19
```
这个文件有30M，试过小文件正常
本地和远程都是win11,PowerShell 7.2.5，安装的时go版的trzsz
[另外我ssh是登录远程win11的PowerShell 7.2.5](https://github.com/PowerShell/Win32-OpenSSH/wiki/DefaultShell)

**Comment by lonnywong** [comment]
看起来跟 https://github.com/trzsz/trzsz-go/issues/12 是同一个问题，在 win11 的 PowerShell 会重复输出一个字符，导致 trzsz 解释失败了。
试试从源码编译一个新的 trzsz 看会不会解决？

```sh
git clone https://github.com/trzsz/trzsz-go.git
cd trzsz-go
go build ./cmd/trzsz
```

**Comment by brucmao** [comment]
我从远程下载文件，编译的trzsz是放在远程，还是本地？
我刚本地编译后，下载还是报错
` .\trzsz.exe ssh -p 6666 bruce@nas.xxx.com`
```
 tsz .\Whore.flac
::TRZSZGO:TRANSFER:S:0.1.8:1
Whore.flac [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | 1.00KB | 7.22KB/s | 1:08:44 ET
illegal base64 data at input byte 9355
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.18.3/x64/src/runtime/debug/stack.go:24 +0x65
github.com/trzsz/trzsz-go/trzsz.NewTrzszError({0xc000216050, 0x44}, {0xc000202014, 0x4}, 0x1)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/comm.go:171 +0x272
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).recvCheck(0x2450?, {0x1e310c, 0x4}, 0x49?, 0xc000093ad0?)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/transfer.go:197 +0x16a
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).recvInteger(0xc000093c40?, {0x1e310c?, 0x2000?}, 0x0?)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/transfer.go:208 +0x25
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).checkInteger(0xc000093c40?, 0x2000)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/transfer.go:216 +0x30
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).sendFiles(0xc00010a0c0, {0xc0000c40a0, 0x1, 0x0?}, {0x0?, 0x0?})
        /home/runner/work/trzsz-go/trzsz-go/trzsz/transfer.go:584 +0x8a6
github.com/trzsz/trzsz-go/trzsz.sendFiles(0xc00010a0c0?, {0xc0000c40a0, 0x1, 0x1}, 0xc0000f8c00, 0x11c7ee60c40?, 0x60?)
        /home/runner/work/trzsz-go/trzsz-go/trzsz/tsz.go:88 +0x19f
github.com/trzsz/trzsz-go/trzsz.TszMain()
        /home/runner/work/trzsz-go/trzsz-go/trzsz/tsz.go:167 +0x7f6
main.main()
        /home/runner/work/trzsz-go/trzsz-go/cmd/tsz/main.go:33 +0x19
```

**Comment by lonnywong** [comment]
放在本地的。我还在用 Win10，我用虚拟机装个 Win11 研究一下。

**Comment by brucmao** [comment]
现在传送文件是用的scp协议吗？用过reverse-ssh的sftp传输还挺快的
https://github.com/linpinger/reverse-ssh

**Comment by lonnywong** [comment]
是服务端输出到 stdout，客户端从 pty 的输出解释出内容。现在看起来 Win11 会重复输出一些字符，导致传输失败。

**Comment by lonnywong** [comment]
我安装 Win11 研究了一下规律，发现每输出一行都会将光标移到上一行的行末，然后重复输出一个字符。

我把那重复的字符过滤掉之后，本地测试是解决了。

可以自己编译一个 `trzsz.exe` 试试看。

```
git clone https://github.com/trzsz/trzsz-go.git
cd trzsz-go
go build ./cmd/trzsz
```

**Comment by brucmao** [comment]
重新编译可以用了，不过下载速度有点慢，我在局域网试了下，速度1.5MB/s，用[sftp](https://github.com/linpinger/reverse-ssh)下载速度23.8MB/s。
trzsz确实方便许多，希望优化下上传下载速度

**Comment by lonnywong** [comment]
速度不是很好搞，下载速度算不错的了，如果是在 Windows 上传，那简直太慢了，要深入去研究 Windows 版的 ssh 到底慢在哪里 https://github.com/PowerShell/openssh-portable 。

**Comment by lonnywong** [comment]
`v0.1.9` 已解决。
