### ISSUE TITLE
[BUG] 从Linux下载文件到Windows失败

### ISSUE THREAD

**Issue by pengtianabc** [trzsz/trzsz-go#4]
1. `Windows`和`Linux`上安装最新版的`0.1.5`版本的`trzsz `
2. 在`Windows`上用`cmd`或者`WindowsTerminal`执行`trzsz ssh x.x.x.x`
3. 在`Linux`主机中执行`tsz xxx`或者`tsz -b xxx`
4. 报错，实际下载到本机的文件只有255KB
```bash
[pengtian@localhost ~]$ tsz -b log.log
illegal base64 data at input byte 71592
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/Cellar/go/1.18.2/libexec/src/runtime/debug/stack.go:24 +0x65
github.com/trzsz/trzsz-go/trzsz.NewTrzszError({0xc0000f4050, 0x44}, {0xc000146090, 0x4}, 0x1)
        /Users/lonnywang/workspace/trzsz-go/trzsz/comm.go:160 +0x272
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).recvCheck(0x117ac?, {0x5516f3, 0x4}, 0x89?, 0xc000113ab8?)
        /Users/lonnywang/workspace/trzsz-go/trzsz/transfer.go:190 +0x152
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).recvInteger(0xc000113c18?, {0x5516f3?, 0x40000?}, 0x0?)
        /Users/lonnywang/workspace/trzsz-go/trzsz/transfer.go:201 +0x25
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).checkInteger(0xc000113c18?, 0x40000)
        /Users/lonnywang/workspace/trzsz-go/trzsz/transfer.go:209 +0x30
github.com/trzsz/trzsz-go/trzsz.(*TrzszTransfer).sendFiles(0xc00012a1e0, {0xc00011e810, 0x1, 0x0?}, {0x0?, 0x0})
        /Users/lonnywang/workspace/trzsz-go/trzsz/transfer.go:517 +0x100c
github.com/trzsz/trzsz-go/trzsz.sendFiles(0xc00012a1e0?, 0xc000122a20, 0x1e?, 0x2?)
        /Users/lonnywang/workspace/trzsz-go/trzsz/tsz.go:79 +0x116
github.com/trzsz/trzsz-go/trzsz.TszMain()
        /Users/lonnywang/workspace/trzsz-go/trzsz/tsz.go:151 +0x756
main.main()
        /Users/lonnywang/workspace/trzsz-go/cmd/tsz/main.go:33 +0x19
```

**Comment by lonnywong** [comment]
感谢反馈，后面我抽空看看。

**Comment by lonnywong** [comment]
奇怪了，我换了不同的 Linux 服务器，在 windows 的 cmd 或 terminal 中 ssh 上去，下载各种不同的文件，没遇到问题。

你的 `ssh` 是什么版本？

只支持 `C:\Windows\System32\OpenSSH\ssh.exe` 那个 ssh，不支持 MSYS 或 Cygwin 中那个 `/usr/bin/ssh`。

那个 `/usr/bin/ssh` 总是会把输入的数据搞漏、搞乱，研究了好久都没解决。

OpenSSH 可以参考 https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse 来安装，我的 Windows10 是默认安装有的。

或者，从 https://github.com/PowerShell/Win32-OpenSSH/releases 下载一个 ssh 来用，我试过也是可以的。

**Comment by pengtianabc** [comment]
真相了，我的环境下的是`msys`下的，刚刚指定成Windows自带的就可以了，刚刚我还尝试了下`wsl`的`ssh`，也都是不可以的~感谢！

**Comment by lonnywong** [comment]
msys 和 wsl 下的 ssh 是 linux 那个版本直接编译出来的，在 windows 上运行有坑，我研究了很久都没解决，只能暂时放弃了。

windows 自带那个 ssh 是在 linux 那个版本的基础上定制的，加了一些 windows 专有的代码，填了坑。
我连具体是什么坑都还没搞懂，也就没搞懂 windows 自带的 ssh 的怎么把坑给填了的。
